### ISSUE TITLE
Dependency resolution failed

### ISSUE THREAD

**Issue by mirus-ua** [okkdev/glailglind#2]
Hello 
I've been trying to scaffold a new project. Here are all deps that I have 
```toml
[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.15.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
```

and I have a problem with the first step 😅 
after running the command `gleam add glailglind --dev` I receive this error 

```bash
gleam add glailglind --dev
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- simplifile
- my_package
- glailglind
```
